apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
 name: log-denied-packets
spec:
 applyOnForward: true
 preDNAT: true
 ingress:
 - action: Log
   destination:
     nets:
     - 173.193.99.247/32
     ports:
     - 32711
   protocol: TCP
 - action: Log
   destination:
     nets:
     - 173.193.99.247/32
     ports:
     - 32711
   protocol: UDP
 selector: ibm.role=='worker_public'
 order: 300
 types:
 - Ingress
